-- =====================================================================
-- GITT - Gestion de Inventario Tecnologico FISEI
-- Esquema fisico Oracle 19c/21c
-- =====================================================================
-- Ejecutar este script conectado al esquema GITT_SCHEMA
-- (CREATE USER GITT_SCHEMA IDENTIFIED BY <pass>; GRANT CONNECT, RESOURCE, DBA TO GITT_SCHEMA;)
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. TABLAS
-- ---------------------------------------------------------------------

CREATE TABLE ROL (
    ID_ROL   NUMBER(10) PRIMARY KEY,
    NOM_ROL  VARCHAR2(30) NOT NULL,
    DES_ROL  VARCHAR2(80),
    CONSTRAINT UQ_ROL_NOM UNIQUE (NOM_ROL)
);

CREATE TABLE USUARIO (
    ID_USU   NUMBER(10) PRIMARY KEY,
    NOM_USU  VARCHAR2(20) NOT NULL,
    APE_USU  VARCHAR2(20) NOT NULL,
    COR_USU  VARCHAR2(40) NOT NULL,
    CLA_USU  VARCHAR2(100) NOT NULL,
    EST_USU  VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,
    ID_ROL   NUMBER(10) NOT NULL,
    CONSTRAINT UQ_USUARIO_COR UNIQUE (COR_USU),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    CONSTRAINT CK_USUARIO_EST CHECK (EST_USU IN ('ACTIVO','INACTIVO','BLOQUEADO'))
);

CREATE TABLE DEPARTAMENTO (
    ID_DEP   NUMBER(10) PRIMARY KEY,
    NOM_DEP  VARCHAR2(40) NOT NULL,
    DES_DEP  VARCHAR2(120)
);

CREATE TABLE UBICACION (
    ID_UBI   NUMBER(10) PRIMARY KEY,
    NOM_UBI  VARCHAR2(40) NOT NULL,
    TIP_UBI  VARCHAR2(20) NOT NULL,
    DES_UBI  VARCHAR2(120),
    ID_DEP   NUMBER(10) NOT NULL,
    CONSTRAINT FK_UBICACION_DEPARTAMENTO FOREIGN KEY (ID_DEP) REFERENCES DEPARTAMENTO(ID_DEP),
    CONSTRAINT CK_UBICACION_TIP CHECK (TIP_UBI IN ('LABORATORIO','AULA','OFICINA','ALMACEN'))
);

CREATE TABLE CATEGORIA (
    ID_CAT   NUMBER(10) PRIMARY KEY,
    NOM_CAT  VARCHAR2(25) NOT NULL,
    DES_CAT  VARCHAR2(120),
    CONSTRAINT UQ_CATEGORIA_NOM UNIQUE (NOM_CAT)
);

CREATE TABLE ESTADO_ARTICULO (
    ID_EST   NUMBER(10) PRIMARY KEY,
    NOM_EST  VARCHAR2(20) NOT NULL,
    DES_EST  VARCHAR2(120),
    CONSTRAINT UQ_ESTADO_NOM UNIQUE (NOM_EST)
);

CREATE TABLE RESPONSABLE (
    ID_RESP   NUMBER(10) PRIMARY KEY,
    NOM_RESP  VARCHAR2(30) NOT NULL,
    APE_RESP  VARCHAR2(30) NOT NULL,
    TIP_RESP  VARCHAR2(20) NOT NULL,
    COR_RESP  VARCHAR2(60),
    TEL_RESP  VARCHAR2(15),
    CONSTRAINT CK_RESP_TIP CHECK (TIP_RESP IN ('DOCENTE','ESTUDIANTE','ADMINISTRATIVO'))
);

CREATE TABLE ARTICULO (
    ID_ART   NUMBER(10) PRIMARY KEY,
    COD_BAR  VARCHAR2(30),
    COD_INS  VARCHAR2(30),
    NOM_ART  VARCHAR2(60) NOT NULL,
    DES_ART  VARCHAR2(200),
    MAR_ART  VARCHAR2(30),
    MOD_ART  VARCHAR2(30),
    SER_ART  VARCHAR2(40),
    FEC_REG  DATE DEFAULT SYSDATE NOT NULL,
    IMG_ART  VARCHAR2(120),
    ACT_ART  CHAR(1) DEFAULT 'S' NOT NULL,
    ID_CAT   NUMBER(10) NOT NULL,
    ID_EST   NUMBER(10) NOT NULL,
    ID_UBI   NUMBER(10) NOT NULL,
    ID_RESP  NUMBER(10),
    CONSTRAINT UQ_ARTICULO_BAR UNIQUE (COD_BAR),
    CONSTRAINT UQ_ARTICULO_INS UNIQUE (COD_INS),
    CONSTRAINT FK_ARTICULO_CATEGORIA   FOREIGN KEY (ID_CAT)  REFERENCES CATEGORIA(ID_CAT),
    CONSTRAINT FK_ARTICULO_ESTADO      FOREIGN KEY (ID_EST)  REFERENCES ESTADO_ARTICULO(ID_EST),
    CONSTRAINT FK_ARTICULO_UBICACION   FOREIGN KEY (ID_UBI)  REFERENCES UBICACION(ID_UBI),
    CONSTRAINT FK_ARTICULO_RESPONSABLE FOREIGN KEY (ID_RESP) REFERENCES RESPONSABLE(ID_RESP),
    CONSTRAINT CK_ARTICULO_ACT CHECK (ACT_ART IN ('S','N'))
);

CREATE TABLE PRESTAMO (
    ID_PRE        NUMBER(10) PRIMARY KEY,
    FEC_PRE       DATE DEFAULT SYSDATE NOT NULL,
    FEC_DEV_PRO   DATE NOT NULL,
    FEC_DEV_REAL  DATE,
    EST_PRE       VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
    OBS_PRE       VARCHAR2(200),
    ID_USU        NUMBER(10) NOT NULL,
    ID_RESP       NUMBER(10) NOT NULL,
    CONSTRAINT FK_PRESTAMO_USUARIO     FOREIGN KEY (ID_USU)  REFERENCES USUARIO(ID_USU),
    CONSTRAINT FK_PRESTAMO_RESPONSABLE FOREIGN KEY (ID_RESP) REFERENCES RESPONSABLE(ID_RESP),
    CONSTRAINT CK_PRESTAMO_EST CHECK (EST_PRE IN ('PENDIENTE','ACTIVO','DEVUELTO','VENCIDO','CANCELADO'))
);

CREATE TABLE DETALLE_PRESTAMO (
    ID_DET_PRE   NUMBER(10) PRIMARY KEY,
    ID_PRE       NUMBER(10) NOT NULL,
    ID_ART       NUMBER(10) NOT NULL,
    EST_ENT      VARCHAR2(30),
    EST_DEV      VARCHAR2(30),
    OBS_DET_PRE  VARCHAR2(200),
    CONSTRAINT FK_DETALLE_PRESTAMO_PRESTAMO FOREIGN KEY (ID_PRE) REFERENCES PRESTAMO(ID_PRE) ON DELETE CASCADE,
    CONSTRAINT FK_DETALLE_PRESTAMO_ARTICULO FOREIGN KEY (ID_ART) REFERENCES ARTICULO(ID_ART)
);

CREATE TABLE MANTENIMIENTO (
    ID_MAN   NUMBER(10) PRIMARY KEY,
    TIP_MAN  VARCHAR2(20) NOT NULL,
    FEC_INI  DATE NOT NULL,
    FEC_FIN  DATE,
    DES_MAN  VARCHAR2(200),
    COS_MAN  NUMBER(10,2),
    PRO_TEC  VARCHAR2(40),
    RES_MAN  VARCHAR2(30),
    ID_ART   NUMBER(10) NOT NULL,
    ID_USU   NUMBER(10) NOT NULL,
    CONSTRAINT FK_MANTENIMIENTO_ARTICULO FOREIGN KEY (ID_ART) REFERENCES ARTICULO(ID_ART),
    CONSTRAINT FK_MANTENIMIENTO_USUARIO  FOREIGN KEY (ID_USU) REFERENCES USUARIO(ID_USU),
    CONSTRAINT CK_MAN_TIP CHECK (TIP_MAN IN ('PREVENTIVO','CORRECTIVO'))
);

CREATE TABLE MOVIMIENTO (
    ID_MOV       NUMBER(10) PRIMARY KEY,
    FEC_MOV      DATE DEFAULT SYSDATE NOT NULL,
    TIP_MOV      VARCHAR2(20) NOT NULL,
    DES_MOV      VARCHAR2(200),
    ID_UBI_ORI   NUMBER(10),
    ID_UBI_DES   NUMBER(10),
    ID_EST_ANT   NUMBER(10),
    ID_EST_NUE   NUMBER(10),
    ID_ART       NUMBER(10) NOT NULL,
    ID_USU       NUMBER(10) NOT NULL,
    CONSTRAINT FK_MOVIMIENTO_UBI_ORI  FOREIGN KEY (ID_UBI_ORI) REFERENCES UBICACION(ID_UBI),
    CONSTRAINT FK_MOVIMIENTO_UBI_DES  FOREIGN KEY (ID_UBI_DES) REFERENCES UBICACION(ID_UBI),
    CONSTRAINT FK_MOVIMIENTO_EST_ANT  FOREIGN KEY (ID_EST_ANT) REFERENCES ESTADO_ARTICULO(ID_EST),
    CONSTRAINT FK_MOVIMIENTO_EST_NUE  FOREIGN KEY (ID_EST_NUE) REFERENCES ESTADO_ARTICULO(ID_EST),
    CONSTRAINT FK_MOVIMIENTO_ARTICULO FOREIGN KEY (ID_ART)     REFERENCES ARTICULO(ID_ART),
    CONSTRAINT FK_MOVIMIENTO_USUARIO  FOREIGN KEY (ID_USU)     REFERENCES USUARIO(ID_USU),
    CONSTRAINT CK_MOV_TIP CHECK (TIP_MOV IN ('TRASLADO','PRESTAMO','DEVOLUCION','MANTENIMIENTO','BAJA','REGISTRO'))
);

CREATE TABLE NOTIFICACION (
    ID_NOT       NUMBER(10) PRIMARY KEY,
    ASU_NOT      VARCHAR2(80) NOT NULL,
    MEN_NOT      VARCHAR2(300) NOT NULL,
    FEC_GEN      DATE DEFAULT SYSDATE NOT NULL,
    FEC_ENV      DATE,
    EST_NOT      VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
    TIP_NOT      VARCHAR2(30) NOT NULL,
    ID_PRE       NUMBER(10),
    ID_USU_DEST  NUMBER(10),
    CONSTRAINT FK_NOTIFICACION_PRESTAMO FOREIGN KEY (ID_PRE)      REFERENCES PRESTAMO(ID_PRE),
    CONSTRAINT FK_NOTIFICACION_USUARIO  FOREIGN KEY (ID_USU_DEST) REFERENCES USUARIO(ID_USU),
    CONSTRAINT CK_NOT_EST CHECK (EST_NOT IN ('PENDIENTE','ENVIADA','LEIDA'))
);

CREATE TABLE AUDITORIA (
    ID_AUD       NUMBER(10) PRIMARY KEY,
    FEC_HOR      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ACC_AUD      VARCHAR2(20) NOT NULL,
    TAB_AUD      VARCHAR2(30) NOT NULL,
    ID_REG_AUD   NUMBER(10) NOT NULL,
    DES_AUD      VARCHAR2(200),
    IP_EQU       VARCHAR2(45),
    ID_USU       NUMBER(10) NOT NULL,
    CONSTRAINT FK_AUDITORIA_USUARIO FOREIGN KEY (ID_USU) REFERENCES USUARIO(ID_USU),
    CONSTRAINT CK_AUD_ACC CHECK (ACC_AUD IN ('INSERT','UPDATE','DELETE','LOGIN','LOGOUT'))
);

-- ---------------------------------------------------------------------
-- 2. SECUENCIAS
-- ---------------------------------------------------------------------

CREATE SEQUENCE SEQ_ROL              START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USUARIO          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DEPARTAMENTO     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_UBICACION        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORIA        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ESTADO_ARTICULO  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_RESPONSABLE      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ARTICULO         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRESTAMO         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DETALLE_PRESTAMO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MANTENIMIENTO    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MOVIMIENTO       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NOTIFICACION     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_AUDITORIA        START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ---------------------------------------------------------------------
-- 3. TRIGGERS DE AUTOINCREMENTO (BEFORE INSERT)
-- ---------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_ROL_BI BEFORE INSERT ON ROL FOR EACH ROW
BEGIN IF :NEW.ID_ROL IS NULL THEN SELECT SEQ_ROL.NEXTVAL INTO :NEW.ID_ROL FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_USUARIO_BI BEFORE INSERT ON USUARIO FOR EACH ROW
BEGIN IF :NEW.ID_USU IS NULL THEN SELECT SEQ_USUARIO.NEXTVAL INTO :NEW.ID_USU FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_DEPARTAMENTO_BI BEFORE INSERT ON DEPARTAMENTO FOR EACH ROW
BEGIN IF :NEW.ID_DEP IS NULL THEN SELECT SEQ_DEPARTAMENTO.NEXTVAL INTO :NEW.ID_DEP FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_UBICACION_BI BEFORE INSERT ON UBICACION FOR EACH ROW
BEGIN IF :NEW.ID_UBI IS NULL THEN SELECT SEQ_UBICACION.NEXTVAL INTO :NEW.ID_UBI FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_CATEGORIA_BI BEFORE INSERT ON CATEGORIA FOR EACH ROW
BEGIN IF :NEW.ID_CAT IS NULL THEN SELECT SEQ_CATEGORIA.NEXTVAL INTO :NEW.ID_CAT FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_ESTADO_BI BEFORE INSERT ON ESTADO_ARTICULO FOR EACH ROW
BEGIN IF :NEW.ID_EST IS NULL THEN SELECT SEQ_ESTADO_ARTICULO.NEXTVAL INTO :NEW.ID_EST FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_RESPONSABLE_BI BEFORE INSERT ON RESPONSABLE FOR EACH ROW
BEGIN IF :NEW.ID_RESP IS NULL THEN SELECT SEQ_RESPONSABLE.NEXTVAL INTO :NEW.ID_RESP FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_ARTICULO_BI BEFORE INSERT ON ARTICULO FOR EACH ROW
BEGIN IF :NEW.ID_ART IS NULL THEN SELECT SEQ_ARTICULO.NEXTVAL INTO :NEW.ID_ART FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_PRESTAMO_BI BEFORE INSERT ON PRESTAMO FOR EACH ROW
BEGIN IF :NEW.ID_PRE IS NULL THEN SELECT SEQ_PRESTAMO.NEXTVAL INTO :NEW.ID_PRE FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_DETALLE_PRE_BI BEFORE INSERT ON DETALLE_PRESTAMO FOR EACH ROW
BEGIN IF :NEW.ID_DET_PRE IS NULL THEN SELECT SEQ_DETALLE_PRESTAMO.NEXTVAL INTO :NEW.ID_DET_PRE FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_MANTENIMIENTO_BI BEFORE INSERT ON MANTENIMIENTO FOR EACH ROW
BEGIN IF :NEW.ID_MAN IS NULL THEN SELECT SEQ_MANTENIMIENTO.NEXTVAL INTO :NEW.ID_MAN FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_MOVIMIENTO_BI BEFORE INSERT ON MOVIMIENTO FOR EACH ROW
BEGIN IF :NEW.ID_MOV IS NULL THEN SELECT SEQ_MOVIMIENTO.NEXTVAL INTO :NEW.ID_MOV FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_NOTIFICACION_BI BEFORE INSERT ON NOTIFICACION FOR EACH ROW
BEGIN IF :NEW.ID_NOT IS NULL THEN SELECT SEQ_NOTIFICACION.NEXTVAL INTO :NEW.ID_NOT FROM DUAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_AUDITORIA_BI BEFORE INSERT ON AUDITORIA FOR EACH ROW
BEGIN IF :NEW.ID_AUD IS NULL THEN SELECT SEQ_AUDITORIA.NEXTVAL INTO :NEW.ID_AUD FROM DUAL; END IF; END;
/

-- ---------------------------------------------------------------------
-- 4. REGLA DE NEGOCIO: un articulo no puede estar en 2 prestamos activos
-- ---------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_PRESTAMO_ACTIVO
BEFORE INSERT ON DETALLE_PRESTAMO
FOR EACH ROW
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM DETALLE_PRESTAMO dp
    JOIN PRESTAMO p ON dp.ID_PRE = p.ID_PRE
    WHERE dp.ID_ART = :NEW.ID_ART
      AND p.EST_PRE IN ('ACTIVO','PENDIENTE');

    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'El articulo ya tiene un prestamo activo. No puede prestarse nuevamente.');
    END IF;
END;
/

-- ---------------------------------------------------------------------
-- 5. TRIGGERS DE AUDITORIA AUTOMATICA (tablas criticas)
-- ---------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_AUD_ARTICULO
AFTER INSERT OR UPDATE OR DELETE ON ARTICULO
FOR EACH ROW
DECLARE
    v_accion VARCHAR2(20);
    v_id_reg NUMBER(10);
    v_usu    NUMBER(10);
BEGIN
    IF INSERTING THEN v_accion := 'INSERT'; v_id_reg := :NEW.ID_ART;
    ELSIF UPDATING THEN v_accion := 'UPDATE'; v_id_reg := :NEW.ID_ART;
    ELSE v_accion := 'DELETE'; v_id_reg := :OLD.ID_ART;
    END IF;

    BEGIN
        v_usu := TO_NUMBER(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'));
    EXCEPTION WHEN OTHERS THEN v_usu := 1;
    END;

    INSERT INTO AUDITORIA (FEC_HOR, ACC_AUD, TAB_AUD, ID_REG_AUD, DES_AUD, ID_USU)
    VALUES (SYSTIMESTAMP, v_accion, 'ARTICULO', v_id_reg,
            'Operacion automatica sobre ARTICULO', NVL(v_usu,1));
END;
/

CREATE OR REPLACE TRIGGER TRG_AUD_PRESTAMO
AFTER INSERT OR UPDATE OR DELETE ON PRESTAMO
FOR EACH ROW
DECLARE
    v_accion VARCHAR2(20);
    v_id_reg NUMBER(10);
    v_usu    NUMBER(10);
BEGIN
    IF INSERTING THEN v_accion := 'INSERT'; v_id_reg := :NEW.ID_PRE;
    ELSIF UPDATING THEN v_accion := 'UPDATE'; v_id_reg := :NEW.ID_PRE;
    ELSE v_accion := 'DELETE'; v_id_reg := :OLD.ID_PRE;
    END IF;

    BEGIN
        v_usu := TO_NUMBER(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'));
    EXCEPTION WHEN OTHERS THEN v_usu := 1;
    END;

    INSERT INTO AUDITORIA (FEC_HOR, ACC_AUD, TAB_AUD, ID_REG_AUD, DES_AUD, ID_USU)
    VALUES (SYSTIMESTAMP, v_accion, 'PRESTAMO', v_id_reg,
            'Operacion automatica sobre PRESTAMO', NVL(v_usu,1));
END;
/

CREATE OR REPLACE TRIGGER TRG_AUD_MANTENIMIENTO
AFTER INSERT OR UPDATE OR DELETE ON MANTENIMIENTO
FOR EACH ROW
DECLARE
    v_accion VARCHAR2(20);
    v_id_reg NUMBER(10);
    v_usu    NUMBER(10);
BEGIN
    IF INSERTING THEN v_accion := 'INSERT'; v_id_reg := :NEW.ID_MAN;
    ELSIF UPDATING THEN v_accion := 'UPDATE'; v_id_reg := :NEW.ID_MAN;
    ELSE v_accion := 'DELETE'; v_id_reg := :OLD.ID_MAN;
    END IF;

    BEGIN
        v_usu := TO_NUMBER(SYS_CONTEXT('USERENV','CLIENT_IDENTIFIER'));
    EXCEPTION WHEN OTHERS THEN v_usu := 1;
    END;

    INSERT INTO AUDITORIA (FEC_HOR, ACC_AUD, TAB_AUD, ID_REG_AUD, DES_AUD, ID_USU)
    VALUES (SYSTIMESTAMP, v_accion, 'MANTENIMIENTO', v_id_reg,
            'Operacion automatica sobre MANTENIMIENTO', NVL(v_usu,1));
END;
/

-- ---------------------------------------------------------------------
-- 6. INDICES DE RENDIMIENTO
-- ---------------------------------------------------------------------

CREATE INDEX IDX_ARTICULO_EST     ON ARTICULO(ID_EST);
CREATE INDEX IDX_ARTICULO_CAT     ON ARTICULO(ID_CAT);
CREATE INDEX IDX_ARTICULO_UBI     ON ARTICULO(ID_UBI);
CREATE INDEX IDX_PRESTAMO_EST     ON PRESTAMO(EST_PRE);
CREATE INDEX IDX_PRESTAMO_RESP    ON PRESTAMO(ID_RESP);
CREATE INDEX IDX_DETALLE_PRE_ART  ON DETALLE_PRESTAMO(ID_ART);
CREATE INDEX IDX_MOVIMIENTO_ART   ON MOVIMIENTO(ID_ART);
CREATE INDEX IDX_NOTIFICACION_USU ON NOTIFICACION(ID_USU_DEST);
CREATE INDEX IDX_AUDITORIA_FEC    ON AUDITORIA(FEC_HOR);

COMMIT;
