module.exports = {
  ROLES: {
    ADMINISTRADOR: 1,
    DOCENTE: 2,
    ESTUDIANTE: 3
  },
  ESTADOS_ARTICULO: {
    DISPONIBLE: 1,
    PRESTADO: 2,
    EN_MANTENIMIENTO: 3,
    DANADO: 4,
    DADO_DE_BAJA: 5
  },
  ESTADOS_PRESTAMO: {
    PENDIENTE: 'PENDIENTE',
    ACTIVO: 'ACTIVO',
    DEVUELTO: 'DEVUELTO',
    VENCIDO: 'VENCIDO',
    CANCELADO: 'CANCELADO'
  },
  TIPOS_NOTIFICACION: {
    PRESTAMO_CREADO: 'PRESTAMO_CREADO',
    DEVOLUCION_PROXIMA: 'DEVOLUCION_PROXIMA',
    PRESTAMO_VENCIDO: 'PRESTAMO_VENCIDO',
    MANTENIMIENTO: 'MANTENIMIENTO'
  }
};
